# Generated by Django 5.0.6 on 2024-05-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prodect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodect',
            old_name='categpry',
            new_name='category',
        ),
    ]
