# Generated by Django 5.0 on 2024-05-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_categpry_prodect_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categorise'},
        ),
    ]
