# Generated by Django 5.0 on 2024-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_categ_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='img',
            field=models.ImageField(upload_to='prodects'),
        ),
    ]
