# Generated by Django 5.0 on 2024-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_prodect_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='img',
            field=models.ImageField(upload_to='prodect'),
        ),
    ]
